import type { MasterSpecification } from "./domain.ts";

function requirement(specification: MasterSpecification, index: number, fallback: string): string {
  return specification.requirements[index]?.id ?? fallback;
}

export function buildGeneratedBackend(specification: MasterSpecification): {
  model: string;
  accessControl: string;
  contracts: string;
  index: string;
} {
  const entityUnion = specification.entities.map((entity) => JSON.stringify(entity)).join(" | ");
  const roleUnion = specification.roles.map((role) => JSON.stringify(role)).join(" | ");
  const productLiteral = JSON.stringify(specification.productName);
  const entityListLiteral = JSON.stringify(specification.entities);
  const roleListLiteral = JSON.stringify(specification.roles);
  const defaultEntityLiteral = JSON.stringify(specification.entities.find((entity) => entity !== "User") ?? specification.entities[0] ?? "Record");
  const ownerRole = JSON.stringify(specification.roles[0] ?? "Owner");

  const model = [
    `export type DomainEntity = ${entityUnion};`,
    `export type Role = ${roleUnion};`,
    "export type DomainRecord = {",
    "  id: string;",
    "  entity: DomainEntity;",
    "  ownerId: string;",
    "  values: Record<string, unknown>;",
    "  archivedAt?: string;",
    "  createdAt: string;",
    "  updatedAt: string;",
    "};",
    `export const domainEntities = ${entityListLiteral} as const satisfies readonly DomainEntity[];`,
    `export const roles = ${roleListLiteral} as const satisfies readonly Role[];`,
    "",
  ].join("\n");

  const accessControl = [
    'import type { DomainRecord, Role } from "../domain/model.js";',
    "",
    "export function canAccess(role: Role, userId: string, record: DomainRecord): boolean {",
    `  if (role === ${ownerRole}) return true;`,
    "  return record.ownerId === userId && !record.archivedAt;",
    "}",
    "",
    "export function requireAccess(allowed: boolean): asserts allowed {",
    '  if (!allowed) throw new Error("FORBIDDEN");',
    "}",
    "",
    "export function requireRole(role: Role | undefined, allowed: readonly Role[]): Role {",
    '  if (!role || !allowed.includes(role)) throw new Error("UNAUTHORIZED");',
    "  return role;",
    "}",
    "",
  ].join("\n");

  const contracts = [
    'import type { DomainEntity, DomainRecord, Role } from "../domain/model.js";',
    "",
    "export type Session = { userId: string; role: Role };",
    "export type CreateRecordInput = { entity: DomainEntity; values: Record<string, unknown> };",
    "export type UpdateRecordInput = { values: Record<string, unknown> };",
    "export type ArchiveRecordInput = { reason?: string };",
    "export type AuditEnvelope<T> = { requirementId: string; actorId: string; action: string; at: string; payload: T };",
    "export type ApiErrorBody = { error: { code: string; message: string } };",
    "export type RecordList = { records: DomainRecord[]; total: number };",
    "",
  ].join("\n");

  const index = [
    'import { createServer, type IncomingMessage, type ServerResponse } from "node:http";',
    'import { randomUUID } from "node:crypto";',
    'import type { DomainEntity, DomainRecord, Role } from "./domain/model.js";',
    'import { domainEntities, roles } from "./domain/model.js";',
    'import { canAccess, requireAccess, requireRole } from "./security/access-control.js";',
    'import type { AuditEnvelope, CreateRecordInput, Session, UpdateRecordInput } from "./api/contracts.js";',
    "",
    `export const service = { name: ${productLiteral}, status: "ready", apiVersion: "v1" } as const;`,
    "const records = new Map<string, DomainRecord>();",
    "const auditLog: AuditEnvelope<unknown>[] = [];",
    `const defaultEntity = ${defaultEntityLiteral} as DomainEntity;`,
    "",
    "function now(): string {",
    "  return new Date().toISOString();",
    "}",
    "",
    "function json(response: ServerResponse, status: number, body: unknown): void {",
    '  response.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });',
    "  response.end(JSON.stringify(body));",
    "}",
    "",
    "function readSession(request: IncomingMessage): Session {",
    '  const roleHeader = request.headers["x-forgeweb-role"];',
    '  const userHeader = request.headers["x-forgeweb-user"];',
    '  const role = requireRole(typeof roleHeader === "string" ? roleHeader as Role : undefined, roles);',
    '  const userId = typeof userHeader === "string" && userHeader.length > 0 ? userHeader : "anonymous";',
    '  if (userId === "anonymous") throw new Error("UNAUTHORIZED");',
    "  return { userId, role };",
    "}",
    "",
    "function audit(requirementId: string, actorId: string, action: string, payload: unknown): void {",
    "  auditLog.push({ requirementId, actorId, action, at: now(), payload });",
    "}",
    "",
    "async function readBody<T>(request: IncomingMessage): Promise<T> {",
    "  const chunks: Buffer[] = [];",
    "  for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));",
    '  if (chunks.length === 0) return {} as T;',
    "  return JSON.parse(Buffer.concat(chunks).toString(\"utf8\")) as T;",
    "}",
    "",
    "function isEntity(value: unknown): value is DomainEntity {",
    "  return typeof value === \"string\" && (domainEntities as readonly string[]).includes(value);",
    "}",
    "",
    "async function handle(request: IncomingMessage, response: ServerResponse): Promise<void> {",
    '  const url = new URL(request.url ?? "/", "http://127.0.0.1");',
    "  const method = request.method ?? \"GET\";",
    "  try {",
    '    if (method === "GET" && url.pathname === "/health") {',
    "      json(response, 200, { ...service, time: now() });",
    "      return;",
    "    }",
    '    if (method === "POST" && url.pathname === "/v1/session") {',
    "      const body = await readBody<{ userId?: string; role?: Role }>(request);",
    '      const role = requireRole(body.role, roles);',
    '      const userId = body.userId && body.userId.length > 0 ? body.userId : randomUUID();',
    "      json(response, 201, { session: { userId, role } satisfies Session });",
    "      return;",
    "    }",
    "    const session = readSession(request);",
    '    if (method === "GET" && url.pathname === "/v1/records") {',
    "      const visible = [...records.values()].filter((record) => canAccess(session.role, session.userId, record));",
    "      json(response, 200, { records: visible, total: visible.length });",
    "      return;",
    "    }",
    '    if (method === "POST" && url.pathname === "/v1/records") {',
    "      const body = await readBody<CreateRecordInput>(request);",
    "      const entity = isEntity(body.entity) ? body.entity : defaultEntity;",
    "      const record: DomainRecord = {",
    "        id: randomUUID(),",
    "        entity,",
    "        ownerId: session.userId,",
    "        values: body.values ?? {},",
    "        createdAt: now(),",
    "        updatedAt: now(),",
    "      };",
    "      records.set(record.id, record);",
    `      audit(${JSON.stringify(requirement(specification, 2, "REQ-003"))}, session.userId, "record.create", { id: record.id, entity: record.entity });`,
    "      json(response, 201, { record });",
    "      return;",
    "    }",
    "    const recordMatch = url.pathname.match(/^\\/v1\\/records\\/([^/]+)(\\/archive)?$/);",
    "    if (recordMatch) {",
    "      const record = records.get(recordMatch[1]);",
    '      if (!record) { json(response, 404, { error: { code: "NOT_FOUND", message: "Record was not found." } }); return; }',
    "      requireAccess(canAccess(session.role, session.userId, record));",
    '      if (method === "GET" && !recordMatch[2]) { json(response, 200, { record }); return; }',
    '      if (method === "PATCH" && !recordMatch[2]) {',
    "        const body = await readBody<UpdateRecordInput>(request);",
    "        record.values = { ...record.values, ...(body.values ?? {}) };",
    "        record.updatedAt = now();",
    `        audit(${JSON.stringify(requirement(specification, 2, "REQ-003"))}, session.userId, "record.update", { id: record.id });`,
    "        json(response, 200, { record });",
    "        return;",
    "      }",
    '      if (method === "POST" && recordMatch[2] === "/archive") {',
    "        record.archivedAt = now();",
    "        record.updatedAt = now();",
    `        audit(${JSON.stringify(requirement(specification, 4, "REQ-005"))}, session.userId, "record.archive", { id: record.id });`,
    "        json(response, 200, { record });",
    "        return;",
    "      }",
    "    }",
    '    if (method === "GET" && url.pathname === "/v1/audit") {',
    `      requireRole(session.role, [${ownerRole}]);`,
    "      json(response, 200, { events: auditLog });",
    "      return;",
    "    }",
    '    json(response, 404, { error: { code: "NOT_FOUND", message: "Route was not found." } });',
    "  } catch (error) {",
    '    const message = error instanceof Error ? error.message : "INTERNAL_ERROR";',
    '    const status = message === "UNAUTHORIZED" ? 401 : message === "FORBIDDEN" ? 403 : 500;',
    "    json(response, status, { error: { code: message, message: message === \"UNAUTHORIZED\" ? \"Authentication is required.\" : message === \"FORBIDDEN\" ? \"You cannot access this record.\" : \"The request could not be completed.\" } });",
    "  }",
    "}",
    "",
    "export function createAppServer() {",
    "  return createServer((request, response) => { void handle(request, response); });",
    "}",
    "",
    'if (import.meta.url === `file://${process.argv[1]}`) {',
    "  const port = Number.parseInt(process.env.PORT ?? \"8788\", 10);",
    '  createAppServer().listen(port, "127.0.0.1", () => {',
    "    console.log(`${service.name} API listening on http://127.0.0.1:${port}`);",
    "  });",
    "}",
    "",
  ].join("\n");

  return { model, accessControl, contracts, index };
}
