/**
 * Architecture Document exporter: renders the plan as a Markdown SDS —
 * system overview, decisions, folder tree, APIs, database, security,
 * deployment. Pure function of the plan; the client offers it as a
 * download.
 */
import type { ArchitecturePlan, FolderNode, NfrScore } from '../architecture.types.ts';

function renderTree(nodes: FolderNode[], prefix = ''): string {
  return nodes
    .map((node, index) => {
      const last = index === nodes.length - 1;
      const branch = `${prefix}${last ? '└── ' : '├── '}${node.name}${node.type === 'directory' ? '/' : ''}`;
      const children = node.children?.length
        ? `\n${renderTree(node.children, `${prefix}${last ? '    ' : '│   '}`)}`
        : '';
      return `${branch}${children}`;
    })
    .join('\n');
}

function decisionRows(plan: ArchitecturePlan): string {
  const { decisions } = plan;
  const rows = [
    ['Architecture', decisions.architecture],
    ['Frontend', decisions.frontendArchitecture],
    ['Backend', decisions.backendArchitecture],
    ['Database', decisions.database],
    ['Authentication', decisions.authentication],
  ] as const;
  return rows
    .map(([area, decision]) => `| ${area} | ${decision.choice} | ${decision.reasoning} |`)
    .join('\n');
}

export function exportMarkdown(plan: ArchitecturePlan): string {
  const lines: string[] = [];
  const push = (text = ''): void => {
    lines.push(text);
  };

  push(`# ${plan.meta.projectName} — Software Design Specification`);
  push();
  push(
    `> Generated by NexArch Architecture Planner · ${plan.meta.generatedAt} · project type: **${plan.meta.projectType}**`,
  );
  push();

  push('## 1. System Overview');
  push();
  push(
    `${plan.meta.projectName} is a ${plan.meta.projectType.toLowerCase()} application built as a **${plan.decisions.architecture.choice}**: ` +
      `a ${plan.decisions.frontendArchitecture.choice.toLowerCase()} client and a ${plan.decisions.backendArchitecture.choice} API over ${plan.database.engine}. ` +
      `${plan.apiModules.length} API modules, ${plan.database.entities.length} entities, ${plan.frontend.pages.length} pages.`,
  );
  push();

  push('## 2. Technology Choices');
  push();
  push('| Area | Choice | Reasoning |');
  push('| --- | --- | --- |');
  push(decisionRows(plan));
  push();

  push('## 3. Module Overview');
  push();
  push('| Module | Controller | Service | Repository |');
  push('| --- | --- | --- | --- |');
  for (const service of plan.services) {
    push(
      `| ${service.module} | ${service.controller} | ${service.service} | ${service.repository} |`,
    );
  }
  push();

  push('## 4. Folder Structure');
  push();
  push('```');
  push(renderTree(plan.folderStructure));
  push('```');
  push();

  push('## 5. API Overview');
  push();
  for (const apiModule of plan.apiModules) {
    push(`### ${apiModule.module} (\`${apiModule.basePath}\`)`);
    push();
    push('| Method | Path | Auth | Description |');
    push('| --- | --- | --- | --- |');
    for (const endpoint of apiModule.endpoints) {
      const auth = endpoint.auth ? (endpoint.roles ? endpoint.roles.join('/') : 'Yes') : 'Public';
      push(`| ${endpoint.method} | \`${endpoint.path}\` | ${auth} | ${endpoint.description} |`);
    }
    push();
  }

  push('## 6. Database Overview');
  push();
  push(`Engine: **${plan.database.engine}**`);
  push();
  for (const entity of plan.database.entities) {
    const relations =
      entity.relations.length > 0
        ? entity.relations.map((r) => `→ ${r.target} (\`${r.foreignKey}\`)`).join(', ')
        : '—';
    push(
      `- **${entity.name}** (\`${entity.tableName}\`) — PK \`${entity.primaryKey}\`; relations: ${relations}; indexes: ${entity.indexes.join(', ') || '—'}`,
    );
  }
  push();
  push('Normalization:');
  push();
  for (const note of plan.database.normalization) {
    push(`- ${note}`);
  }
  push();

  push('## 7. Security Overview');
  push();
  push(`- **Authentication:** ${plan.security.authentication.join(', ')}`);
  push(`- **Sessions:** ${plan.security.sessionStrategy}`);
  push(`- **Authorization:** ${plan.security.authorization}`);
  push(`- **Password policy:** ${plan.security.passwordPolicy.join('; ')}`);
  push(`- **Rate limiting:** ${plan.security.rateLimiting.join('; ')}`);
  push(`- **Validation:** ${plan.security.validation}`);
  push(`- **Headers:** ${plan.security.headers.join('; ')}`);
  push(`- **CORS:** ${plan.security.cors}`);
  push();

  push('## 8. Module Dependencies');
  push();
  for (const edge of plan.dependencyGraph.edges) {
    const from =
      plan.dependencyGraph.nodes.find((node) => node.id === edge.from)?.label ?? edge.from;
    const to = plan.dependencyGraph.nodes.find((node) => node.id === edge.to)?.label ?? edge.to;
    push(`- ${from} → ${to} (${edge.reason})`);
  }
  push();

  push('## 9. Deployment Overview');
  push();
  push(
    '- Dockerized services (multi-stage builds, non-root runtime) composed with MySQL behind nginx.',
  );
  push('- nginx serves the static client and proxies `/api` — single origin, no production CORS.');
  push(
    '- Health endpoints (`/health/live`, `/health/ready`) wired for orchestrator probes; graceful shutdown on SIGTERM.',
  );
  push();

  push('## 10. Scalability & Non-Functional Targets');
  push();
  for (const item of plan.futureScalability) {
    push(`- **${item.concern}:** ${item.recommendation} _(trigger: ${item.trigger})_`);
  }
  push();
  push('| Quality | Score | Notes |');
  push('| --- | --- | --- |');
  const nfrRows: [string, NfrScore][] = [
    ['Performance', plan.nonFunctional.performance],
    ['Maintainability', plan.nonFunctional.maintainability],
    ['Security', plan.nonFunctional.security],
    ['Scalability', plan.nonFunctional.scalability],
    ['Availability', plan.nonFunctional.availability],
    ['Reliability', plan.nonFunctional.reliability],
  ];
  for (const [quality, value] of nfrRows) {
    push(`| ${quality} | ${value.score}/10 | ${value.notes} |`);
  }
  push();

  return lines.join('\n');
}

